Add test for windows x64 gun target

diff --git a/.github/workflows/build-and-tests.yml b/.github/workflows/build-and-tests.yml
--- a/.github/workflows/build-and-tests.yml
+++ b/.github/workflows/build-and-tests.yml
@@ -428,8 +428,29 @@ jobs:
             target: aarch64-unknown-linux-gnu
           - host: windows-11-arm
             target: aarch64-pc-windows-msvc
+          - host: windows-latest
+            target: x86_64-pc-windows-gnu
+            msystem: ucrt64
+            toolchain: ucrt-x86_64
+            setup: |
+              rustup default
+              rustup set default-host x86_64-pc-windows-gnu
+              rustup default nightly
+              rustup install nightly-x86_64-pc-windows-gnu
+              rustup install nightly-2025-07-25
+              rustup default nightly-x86_64-pc-windows-gnu
+              rustup override set nightly-2025-07-25
+              rustup show
+            build: >-
+              set -e &&
+              which node &&
+              rustup target add x86_64-pc-windows-gnu &&
+              rustup component add rust-src --toolchain nightly-2025-07-25-x86_64-pc-windows-gnu &&
+              npm run build:napi -- --release --target x86_64-pc-windows-gnu
+            env:
+              MINGW_ARCH: ucrt64
         node:
-          - '18.20.0'
+          # - '18.20.0'
           - 24
         include:
           - settings:
@@ -456,10 +477,41 @@ jobs:
       - name: Checkout Commit
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       - name: Setup Node
+        if: ${{ matrix.settings.target != 'x86_64-pc-windows-gnu' }}
         uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
         with:
           node-version: ${{ matrix.node }}
           check-latest: true
+      - uses: msys2/setup-msys2@v2
+        if: ${{ matrix.settings.target == 'x86_64-pc-windows-gnu' }}
+        with:
+          msystem: ${{ matrix.settings.msystem }}
+          install: mingw-w64-${{ matrix.settings.toolchain }}-toolchain base-devel binutils git
+          pacboy: >-
+            aria2:p
+            ca-certificates
+            rustup:p
+            nodejs:p
+            rust-wasm:p
+            rust-src:p
+          update: true
+          path-type: inherit
+          #location: C:\
+          release: false
+      - name: Setup toolchain
+        run: ${{ matrix.settings.setup }}
+        if: ${{ matrix.settings.setup }}
+      - name: remove nodejs from msvc
+        if: ${{ matrix.settings.target == 'x86_64-pc-windows-gnu' }}
+        shell: msys2 {0}
+        run: |
+          echo $(which node)
+          which npm
+          if which node | grep -i "$MSYSTEM";then
+            echo "node is locate at $(which node)"
+          else
+            echo "node is not Gnu." && exit 1
+          fi
       - name: Install and Cache Node Dependencies
         uses: ./.github/actions/install-and-cache-node-deps
       - name: Download napi artifacts
@@ -471,17 +523,29 @@ jobs:
         uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
         with:
           name: bindings-wasm
+      - name: Build and test Rollup (msys2)
+        if: ${{ matrix.settings.target == 'x86_64-pc-windows-gnu' }}
+        run: |
+          ${{ matrix.settings.build }}
+          which node
+          echo "const os = require('os'); console.log(os.type())" | node -
+          npm run ${{ matrix.command || 'ci:test:only' }}
+        shell: msys2 {0}
+        env:
+          CI: true
+          MINGW_ARCH: ucrt64
       - name: Build and test Rollup
+        if: ${{ matrix.settings.target != 'x86_64-pc-windows-gnu' }}
         run: npm run ${{ matrix.command || 'ci:test:only' }}
         env:
           CI: true
-      - name: Upload coverage
-        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
-        if: matrix.coverage
-        with:
-          fail_ci_if_error: true
-          verbose: true
-          token: ${{ secrets.CODECOV_TOKEN }}
+      # - name: Upload coverage
+      #   uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
+      #   if: matrix.coverage
+      #   with:
+      #     fail_ci_if_error: true
+      #     verbose: true
+      #     token: ${{ secrets.CODECOV_TOKEN }}
 
   publish:
     permissions:
